#!/bin/bash

# Programm to output a system information page

TITLE="Sytem Information Report For $HOSTNAME"
CURRENT_TIME="$(date +"%x %r %Z")"
TIMESTAMP="Generated $CURRENT_TIME, by $USER"


report_uptime () {
    cat <<- EOF
        <h2>System Uptime</h2>
        <pre>$(uptime)</pre>
EOF
    return
}

report_disk_space () {
    cat <<-EOF
        <h2>Disk Space Utilization</h2>
        <pre>$(df -h)</pre>
EOF
    return
}

report_home_space () {
    cat  <<-EOF
        <h2>Home Space Utilization</h2>
        <pre>$(dust -d 0 -cpb /home/*)</pre>
EOF
    return
}

cat <<- _EOF_
<html>
   <head>
       <title>$TITLE</title>
   </head>
   <body>
            <h1>$TITLE</h1>
            <p>$TIMESTAMP</p>
            $(report_uptime)
            $(report_disk_space)
            $(report_home_space)
   </body>
</html>
_EOF_
